<?

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PetController;
use App\Http\Controllers\ConsultationController;
use App\Http\Controllers\MedicalController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;

Route::get('/dashboard', [UserController::class, 'userRedirect'])
    ->middleware(['verified'])
    ->name('dashboard');

Route::get('/users', [AdminController::class, 'index'])->name('users');
Route::get('/appointments', [AdminController::class, 'index'])->name('appointments');
Route::get('/pets', [PetController::class, 'index'])->name('pets');

// Auto generated by Breeze
Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

Route::patch('/users/{user}/role', [UserController::class, 'updateRole'])->name('users.updateRole');
Route::patch('/api/users/{user}/deactivate', [UserController::class, 'deactivate']);
Route::patch('/api/users/{user}/activate', [UserController::class, 'activate']);

// Appointment + Pets
Route::prefix('my_appointments')->name('my_appointments.')->group(function () {
    Route::patch('/{appointment}/status/{status}', [AppointmentController::class, 'updateStatus'])->name('updateStatus');
});
Route::resource('appointments', AppointmentController::class);

Route::get('/my_pets', [UserController::class, 'pets'])->name('my_pets');
Route::prefix('pets')->name('pets.')->group(function () {
    Route::get('{pet_code}/edit', [PetController::class, 'edit'])->name('edit');
    Route::put('{pet_code}', [PetController::class, 'update'])->name('update');
    Route::delete('{pet_code}', [PetController::class, 'destroy'])->name('destroy');
});

Route::get('/vet_team', [AdminController::class, 'veterinarians'])->name('vet_team');
Route::get('/appointments', [AdminController::class, 'appointments'])->name('appointments');

Route::post('/vets/{vet}/specialization', [UserController::class, 'updateSpecialization'])->name('vets.updateSpecialization');
Route::post('/vets/{vet}/toggle-active', [UserController::class, 'toggleActiveStatus']);

Route::get('/api/vets/active', function () {
    $activeVets = DB::table('vet_profile as vp')
        ->join('users as u', 'vp.user_id', '=', 'u.id')
        ->where('vp.is_active', 1)
        ->select('u.id', 'u.name','vp.specialization')
        ->get();
    return response()->json($activeVets);
})->name('api.vets.active');

Route::post('/appointments/{id}/assign-vet', [AppointmentController::class, 'assignVet'])->name('appointments.assignVet');
Route::post('/assigned-vet/remove', [AdminController::class, 'remove']);

Route::get('/consultations', [AdminController::class, 'consultations'])->name('consultations');

Route::get('/consultations', [ConsultationController::class, 'index'])->name('consultations.index');

Route::resource('consultations', ConsultationController::class);
Route::resource('medical', MedicalController::class);
Route::get('consultations/{consultation}/download', [ConsultationController::class, 'download'])->name('consultations.download');

Route::get('/search', [AdminController::class, 'search'])->name('search');
