<?php

use App\Http\Controllers\Auth\GoogleAuthController;
use App\Http\Controllers\Auth\FacebookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PetController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductRequestController;
use App\Models\User;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Laravel\Socialite\Facades\Socialite;
use Illuminate\Support\Facades\DB;

require __DIR__.'/auth.php';

Route::get('/', function () {
    return view('HomePage');})->name('home');

Route::get('/dashboard', [UserController::class, 'userRedirect'])
    ->middleware(['auth', 'verified'])
    ->name('dashboard');
    
Route::get('/users', [AdminController::class, 'index'])->middleware(['auth'])->name('users');
Route::get('/pets', [PetController::class, 'index'])->middleware(['auth'])->name('pets');

//Auto generated by breeze
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::patch('/users/{user}/role', [UserController::class, 'updateRole'])->name('users.updateRole');

Route::middleware('web')->group(function () {
    Route::get('auth/google', [GoogleAuthController::class, 'redirect'])->name('google.login');
    Route::get('auth/google/callback', [GoogleAuthController::class, 'callback']);
});


Route::get('/auth/facebook', [FacebookController::class, 'redirectToFacebook'])->name('facebook.login');
Route::get('/auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

#region Appointment and Pets

//Appointments Route
Route::prefix('my_appointments')->name('my_appointments.')->group(function () {
    Route::get('/', [AppointmentController::class, 'appointments'])->name('index');
    Route::post('/', [AppointmentController::class, 'store'])->name('store');
    Route::patch('/{appointment}/status/{status}', [AppointmentController::class, 'updateStatus'])->name('updateStatus');
});
Route::resource('appointments', AppointmentController::class);

//Pet Route
Route::get('/my_pets', [UserController::class, 'pets'])->name('my_pets');
Route::prefix('pets')->name('pets.')->group(function () {
    Route::get('{pet_code}/edit', [PetController::class, 'edit'])->name('edit');
    Route::put('{pet_code}', [PetController::class, 'update'])->name('update');
    Route::delete('{pet_code}', [PetController::class, 'destroy'])->name('destroy');
});

Route::get('/vet_team', [AdminController::class, 'veterinarians'])->name('vet_team');

Route::get('/appointments', [AdminController::class, 'appointments'])->name('appointments');
#endregion

Route::post('/vets/{vet}/specialization', [UserController::class, 'updateSpecialization'])
    ->name('vets.updateSpecialization');
Route::post('/vets/{vet}/toggle-active', [UserController::class, 'toggleActiveStatus']);

// routes/api.php or web.php with middleware 'auth' and 'admin'
Route::get('/api/vets/active', function () {
    $activeVets = DB::table('vet_profile as vp')
        ->join('users as u', 'vp.user_id', '=', 'u.id')
        ->where('vp.is_active', 1)
        ->select('u.id', 'u.name','vp.specialization')
        ->get();
    return response()->json($activeVets);
})->name('api.vets.active');
// web.php (since you are using CSRF and Blade)
//Route::post('/assign-vet', [AdminController::class, 'assignVet'])->name('assign');
Route::post('/appointments/{id}/assign-vet', [AppointmentController::class, 'assignVet'])
    ->name('appointments.assignVet');
Route::post('/assigned-vet/remove', [AdminController::class, 'remove']);

Route::get('/consultations', [AdminController::class, 'consultations'])->name('consultations');


use App\Http\Controllers\ConsultationController;
use App\Http\Controllers\MedicalController;

Route::prefix('consultations')->middleware(['auth'])->group(function () {
    Route::get('/', [ConsultationController::class, 'index'])->name('consultations.index');
    
});

Route::prefix('consultations')->middleware(['auth'])->group(function () {
    Route::get('/', [ConsultationController::class, 'index'])->name('consultations.index');
});

Route::resource('consultations', ConsultationController::class);
Route::resource('medical', MedicalController::class);
Route::get('consultations/{consultation}/download', [ConsultationController::class, 'download'])
    ->name('consultations.download');
Route::get('/search', [AdminController::class, 'search'])->name('search');

// Product routes
Route::get('/products', [ProductController::class, 'index'])->name('Products.ProductList');
Route::get('/products/search', [ProductController::class, 'search'])->name('Products.ProductSearch');
Route::get('/products/{product}', [ProductController::class, 'show'])->name('Products.ProductView');

// Authenticated routes
Route::middleware('auth')->group(function () {
    // Customer product request routes
    Route::get('/product-requests', [ProductRequestController::class, 'index'])->name('ProductRequests.ProductRequestList');
    Route::get('/product-requests/create/{product}', [ProductRequestController::class, 'create'])->name('ProductRequests.ProductCreateRequest');
    Route::post('/product-requests', [ProductRequestController::class, 'store'])->name('product-requests.store');
    Route::get('/product-requests/{productRequest}', [ProductRequestController::class, 'show'])->name('product-requests.show');
    Route::patch('/product-requests/{productRequest}/cancel', [ProductRequestController::class, 'cancel'])->name('product-requests.cancel');
});