<?php

use App\Http\Controllers\Auth\GoogleAuthController;
use App\Http\Controllers\Auth\FacebookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PetController;
use App\Models\User;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Laravel\Socialite\Facades\Socialite;

require __DIR__.'/auth.php';

Route::get('/', function () {
    return view('HomePage');})->name('home');

Route::get('/dashboard', [UserController::class, 'userRedirect'])
    ->middleware(['auth', 'verified'])
    ->name('dashboard');
    
Route::get('/users', [AdminController::class, 'index'])->middleware(['auth'])->name('users');
Route::get('/pets', [PetController::class, 'index'])->middleware(['auth'])->name('pets');

//Auto generated by breeze
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::patch('/users/{user}/role', [UserController::class, 'updateRole'])->name('users.updateRole');

Route::middleware('web')->group(function () {
    Route::get('auth/google', [GoogleAuthController::class, 'redirect'])->name('google.login');
    Route::get('auth/google/callback', [GoogleAuthController::class, 'callback']);
});


Route::get('/auth/facebook', [FacebookController::class, 'redirectToFacebook'])->name('facebook.login');
Route::get('/auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

#region Appointment and Pets
//Appointments Route
Route::prefix('my_appointments')->name('my_appointments.')->group(function () {
    Route::get('/', [AppointmentController::class, 'appointments'])->name('index');
    Route::post('/', [AppointmentController::class, 'store'])->name('store');
});
Route::resource('appointments', AppointmentController::class);

//Pet Route
Route::get('/my_pets', [UserController::class, 'pets'])->name('my_pets');
Route::prefix('pets')->name('pets.')->group(function () {
    Route::get('{pet_code}/edit', [PetController::class, 'edit'])->name('edit');
    Route::put('{pet_code}', [PetController::class, 'update'])->name('update');
    Route::delete('{pet_code}', [PetController::class, 'destroy'])->name('destroy');
});

Route::get('/vet_team', [AdminController::class, 'veterinarians'])->name('vet_team');

Route::get('/appointments', [AdminController::class, 'appointments'])->name('appointments');
#endregion