<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PetController;

use App\Http\Controllers\Auth\FacebookController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Models\User;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| This file contains all the web routes for your Laravel application.
*/

// Public welcome page (Homepage)
Route::get('/', function () {
    return view('welcome');
});

// Authenticated dashboard view
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Routes that require the user to be authenticated
Route::middleware(['auth'])->group(function () {

    // Appointment Management Routes
    Route::get('/appointments', [AppointmentController::class, 'index'])->name('appointments.index'); // View all appointments
    Route::get('/appointments/create', [AppointmentController::class, 'create'])->name('appointments.create'); // Show appointment creation form
    Route::post('/appointments', [AppointmentController::class, 'store'])->name('appointments.store'); // Save new appointment

    Route::resource('pets', PetController::class); // Resourceful routes for PetController

    // Profile Management Routes
    Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit'); // Show profile edit form
    Route::post('/profile/update', [ProfileController::class, 'update'])->name('profile.update'); // Save profile updates


});

// Authentication routes
require __DIR__.'/auth.php';



Route::get('/', function () {
    return view('HomePage');})->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/users', [AdminController::class, 'index'])->middleware(['auth'])->name('users');
Route::get('/pets', [PetController::class, 'index'])->middleware(['auth'])->name('pets');

//Auto generated by breeze
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::get('/user_dashboard', function () {
    return view('user_dashboard');
})->middleware(['auth']);

Route::get('auth/google', function () {
    return Socialite::driver('google')->redirect();
})->name('google.login');

// Handle callback from Google
Route::get('auth/google/callback', function () {
    $googleUser = Socialite::driver('google')->user();

    $user = User::firstOrCreate(
        ['email' => $googleUser->getEmail()],
        [
            'name' => $googleUser->getName(),
            'password' => bcrypt(Str::random(24)),
            'google_id' => $googleUser->getId(),
        ]
    );

    Auth::login($user);

    return redirect()->intended('/dashboard');
});

Route::get('/auth/facebook', [FacebookController::class, 'redirectToFacebook'])->name('facebook.login');
Route::get('/auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

Route::get('/my_appointments', [AppointmentController::class, 'appointments'])->name('my_appointments');
Route::post('/my_appointments', [AppointmentController::class, 'store'])->name('store_appointments');
Route::resource('appointments', AppointmentController::class); //contains update and delete

Route::get('/my_pets', [UserController::class, 'pets'])->name('my_pets');

Route::get('/appointments', [AdminController::class, 'appointments'])->name('appointments');